#!/usr/bin/env php
<?php
require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use EkoJunaidiSalam\App\Command\HelperCommand;

$app = new Application("SPPT-TI Helper","1.0.0");

$app->addCommands([new HelperCommand()]);
$app->run();